site_name: BatchGenie Landing Page
theme:
  name: material
  custom_dir: overrides #Remember to save mkdocs.yml to refresh the overrides
  favicon: favicon.svg
  language: en
  # palette:
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     toggle:
  #       icon: material/brightness-7
  #       name: Switch to dark mode
  #     primary: indigo
  #     accent: orange
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
    #   primary: indigo
    #   accent: orange

extra_css:
  - extra.css

nav: []

extra:
  generator: false #Hide footer

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.emoji: #Used for icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons/ #Icons can be a bit slow to update when adding new
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower